AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  offline-development-api

Globals:
  Function:
    Timeout: 60

Resources:
  GetAllItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get-all/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        GetItem:
          Type: Api
          Properties:
            Path: /items/
            Method: get
      Environment:
        Variables:
          USE_LOCAL_DYNAMODB: "true"

  GetItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get-item/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        GetItem:
          Type: Api
          Properties:
            Path: /items/{itemId}
            Method: get
      Environment:
        Variables:
          USE_LOCAL_DYNAMODB: "true"

  GetPythonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: python/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        GetItem:
          Type: Api
          Properties:
            Path: /python
            Method: get
      Environment:
        Variables:
          USE_LOCAL_DYNAMODB: "true"
